import re

def is_tech_job(job_title):
    tech_keywords = [
        "fullstack",
        "full stack",
        "full-stack",
        "frontend",
        "front end",
        "front-end",
        "backend",
        "back end",
        "back-end",
        "devops",
        "ux",
        "ui",
        "ux/ui",
        "ui/ux",
        "sql",
        "research engineer",
        "research engineering",
        "data engineer",
        "data engineering",
        "software engineering",
        "software engineer",
        "software developer",
        "web developer",
        "full stack developer",
        "frontend developer",
        "backend developer",
        "devops engineer",
        "devops engineering",
        "cloud engineer",
        "cloud engineering",
        "data scientist",
        "machine learning engineer",
        "ai engineer",
        "ai engineering",
        "ml engineer",
        "ml engineering",
        "product manager",
        "product owner",
        "scrum master",
        "ux designer",
        "ui designer",
        "qa engineer",
        "qa engineering",
        "quality assurance engineer",
        "test engineer",
        "test engineering",
        "network administrator",
        "security engineer",
        "security engineering",
        "database administrator",
        "dba",
        "systems administrator",
        "technical support",
        "it support",
        "it specialist",
        "it consultant",
        "it analyst",
        "it coordinator",
        "it manager",
        "it director",
        "it architect",
        "it strategist",
        "it engineer",
        "it engineering",
        "cyber security",
        "product management",
        "web security",
        "information technology"
        "information systems",
        "mobile developer",
        "ios developer",
        "android developer",
        "game developer",
        "artifical intelligence",
        "data analyst",
        "business intelligence analyst",
        "agile coach",
        "devops",
        "sre",
        "site reliability engineer",
        "site reliability engineering",
        "cloud architect",
        "solutions architect",
        "cybersecurity analyst",
        "information security",
        "network engineer",
        "network engineering",
        "systems engineer",
        "systems engineering",
        "software architect",
        "data engineer",
        "big data engineer",
        "big data engineering",
        "blockchain developer",
        "embedded systems engineer",
        "firmware engineer",
        "firmware engineering",
        "hardware engineer",
        "hardware engineering",
        "it project manager",
        "tech lead",
        "cto",
        "chief technology officer",
        "vp of engineering",
        "director of engineering",
        "head of it",
        "it manager",
        "release engineer",
        "release engineering",
        "build engineer",
        "build engineering",
        "automation engineer",
        "automation engineering",
        "etl developer",
        "salesforce developer",
        "salesforce administrator",
        "crm developer",
        "erp developer",
        "sap consultant",
        "oracle developer",
        "database developer",
        "data warehouse developer",
        "bi developer",
        "reporting analyst",
        "sql developer",
        "nosql developer",
        "front-end engineer",
        "front-end engineering",
        "back-end engineer",
        "back-end engineering",
        "full-stack engineer",
        "full-stack engineering",
        "devops specialist",
        "cloud specialist",
        "aws specialist",
        "azure specialist",
        "gcp specialist",
        "kubernetes engineer",
        "kubernetes engineering",
        "docker specialist",
        "microservices architect",
        "api developer",
        "mobile app developer",
        "cross-platform developer",
        "react native developer",
        "flutter developer",
        "unity developer",
        "unreal engine developer",
        "ar developer",
        "vr developer",
        "computer vision engineer",
        "computer vision engineering",
        "nlp engineer",
        "nlp engineering",
        "data mining engineer",
        "data mining engineering",
        "bioinformatics scientist",
        "quantum computing researcher",
        "penetration tester",
        "ethical hacker",
        "malware analyst",
        "forensic analyst",
        "security operations center",
        "devsecops engineer",
        "devsecops engineering",
        "cloud security engineer",
        "cloud security engineering",
        "network security engineer",
        "network security engineering",
        "information systems security",
        "it auditor",
        "technology consultant",
        "digital transformation",
        "robotic process automation",
        "rpa developer",
        "low-code developer",
        "no-code developer",
        "sys admin",
        "linux administrator",
        "windows administrator",
        "virtualization specialist",
        "vmware specialist",
        "citrix engineer",
        "citrix engineering",
        "voice engineer",
        "voice engineering",
        "voip engineer",
        "voip engineering",
        "telecommunications engineer",
        "telecommunications engineering",
        "wireless network engineer",
        "wireless network engineering",
        "iot developer",
        "embedded developer",
        "fpga engineer",
        "fpga engineering",
        "asic designer",
        "technology analyst"
        # Linguagens de programação
        "python",
        "java",
        "javascript",
        "typescript",
        "c#",
        "c++",
        "ruby",
        "php",
        "scala",
        "go",
        "golang",
        "rust",
        "swift",
        "kotlin",
        "matlab",
        "perl",
        "haskell",
        "julia",
        "groovy",
        "objective-c",
        "vba",
        "cobol",
        "fortran",
        "assembly",
        "pascal",
        "delphi",
        "lisp",
        "prolog",
        "abap",
        "visual basic",
        "f#",
        "dart",
        "elixir",
        "erlang",
        "clojure",
        "ocaml",
        "bash",
        "powershell",
        "sql",
        "nosql",
        "html",
        "css",
        "xml",
        "yaml",
        # Frameworks and libs
        "react",
        "angular",
        "vue",
        "node",
        "nodejs",
        "node.js",
        "express.js",
        "expressjs",
        "express",
        "django",
        "flask",
        "spring",
        "asp.net",
        "laravel",
        "rails",
        "jquery",
        "bootstrap",
        "material-ui",
        "tailwind",
        "gatsby",
        "next.js",
        "nuxt",
        "svelte",
        "ember",
        "backbone",
        "meteor",
        "symfony",
        "codeigniter",
        "zend",
        "flask",
        "fastapi",
        "tornado",
        "pyramid",
        "play framework",
        "akka",
        "hibernate",
        "entity framework",
        "xamarin",
        "ionic",
        "react native",
        "flutter",
        "electron",
        # Database and storage
        "mysql",
        "postgresql",
        "oracle",
        "sql server",
        "mongodb",
        "cassandra",
        "redis",
        "elasticsearch",
        "neo4j",
        "dynamodb",
        "couchbase",
        "firebase",
        "mariadb",
        "sqlite",
        "hbase",
        "influxdb",
        "graphql",
        "apollo",
        # Cloud e DevOps
        "aws",
        "azure",
        "gcp",
        "google cloud",
        "heroku",
        "digitalocean",
        "openshift",
        "kubernetes",
        "docker",
        "jenkins",
        "gitlab",
        "github actions",
        "travis",
        "circleci",
        "ansible",
        "puppet",
        "chef",
        "terraform",
        "vagrant",
        "prometheus",
        "grafana",
        "elk stack",
        # Big Data e Machine Learning
        "hadoop",
        "spark",
        "kafka",
        "airflow",
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "pandas",
        "numpy",
        "scipy",
        "matplotlib",
        "seaborn",
        "keras",
        "opencv",
        "nltk",
        "spacy",
        # Frontend e design
        "sass",
        "less",
        "webpack",
        "babel",
        "gulp",
        "grunt",
        "npm",
        "yarn",
        "photoshop",
        "illustrator",
        "sketch",
        "figma",
        "invision",
        "zeplin",
        # Mobile
        "android studio",
        "xcode",
        "cordova",
        "phonegap",
        "unity",
        "unreal engine",
        # Testing e QA
        "selenium",
        "appium",
        "junit",
        "pytest",
        "jest",
        "mocha",
        "jasmine",
        "karma",
        "cucumber",
        # Other techs
        "restful",
        "soap",
        "websocket",
        "oauth",
        "jwt",
        "blockchain",
        "ethereum",
        "solidity",
        "webassembly",
        "pwa",
        "serverless",
        "microservices",
        "docker-compose",
        "nginx",
        "apache",
        "tomcat",
        "iis",
        "memcached",
        "rabbitmq",
        "activemq",
        "celery",
        "redux",
        "vuex",
        "rxjs",
        "webpack",
        "gulp",
        "grunt",
        "babel",
        "eslint",
        "prettier",
        "swagger",
        "postman",
        "jira",
        "confluence",
        "trello",
        "asana",
        "slack",
        "git",
        "svn",
        "mercurial",
    ]

    job_title_lower = job_title.lower()
    words = re.findall(r'\b\w+\b', job_title_lower)

    for keyword in tech_keywords:
        if ' ' in keyword:
            if all(word in words for word in keyword.split()):
                return True
        elif keyword in words:
            return True
    
    return False
